### ISSUE TITLE
Builds of YT Music crash, while they work fine when build with the ReVanced Manager

### ISSUE THREAD

**Issue by xXShoggothXx** [reisxd/revanced-builder#482] opened 2022-09-29 10:44 UTC
**Describe the bug**
Even when only build with the MicroG Patch YT music instantly crashes while I could activate every patch in the ReVanced Manager and it works fine.

**To Reproduce**

Just build with the recommended app version, happens on ARMv7 and ARMv8

**revanced-builder Version:** [e.g. v1.2.10]

revanced-builder v3.4.11

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Comment by reisxd** [comment] 2022-09-29 12:36
Dupe of #474.

**Closed by reisxd** 2022-09-29 12:36 UTC
