### ISSUE TITLE
Revanced root building not working with Android device method

### ISSUE THREAD

**Issue by binoysankar** [reisxd/revanced-builder#213] opened 2022-08-10 12:30 UTC
Describe the bug:

When trying to build revanced apk/file in Android phone (rooted) I am getting the below error (PFA Screenshot).
During the building process I gave Termux the root access as well. With Microg option the build is successful.
![Screenshot_20220810-175327_Chrome](https://user-images.githubusercontent.com/10673905/183901403-6c613d84-bdc9-4ac4-8e53-a0ff6d5d895f.png)
![Screenshot_20220810-175321_Termux](https://user-images.githubusercontent.com/10673905/183901422-45a15cb5-52fa-4c59-899d-871437c9d64a.png)

**Comment by shrihanDev** [comment] 2022-08-10 15:01
This is a known issue. _I haven't got the time to test and fix it (I do have a rooted device)._

**Comment by binoysankar** [comment] 2022-08-10 15:10
> This is a known issue. _I haven't got the time to test and fix it (I do have a rooted device)._

Sure. Np. Thanks for the update. I was looking for the rooted varient and saw this error while building.
Eagerly waiting for the fix some day :)

**Comment by reisxd** [comment] 2022-08-12 16:03
Can you try clearing Termuxs cache and if it still doesn't work, clearing data and installing Builder again?

**Comment by munchycool** [comment] 2022-08-13 11:18
Hello @reisxd ..long time no see ;)

I tried on a fresh brand new install of Miui on poco x3 pro and I think issue is arising since on some dynamic partition devices with super you cannot mount system as rw even after rooting ...

you first need to do this
https://forum.xda-developers.com/t/closed-script-android-10-universal-mount-systemrw-superrw-featuring-makerw-read-write.4247311/

would it be a better idea to make a magisk module instead?

**Comment by reisxd** [comment] 2022-08-13 11:34
> Hello @reisxd ..long time no see ;)
> 
> I tried on a fresh brand new install of Miui on poco x3 pro and I think issue is arising since on some dynamic partition devices with super you cannot mount system as rw even after rooting ...
> 
> you first need to do this
> https://forum.xda-developers.com/t/closed-script-android-10-universal-mount-systemrw-superrw-featuring-makerw-read-write.4247311/
> 
> would it be a better idea to make a magisk module instead? 

Sadly, I don't know how to write magisk module instead, and well... I litterally didn't understand anything you said because I never rooted my devices. 😅

**Comment by munchycool** [comment] 2022-08-13 18:48
can we add a timeout feature? lets say its stuck at trying to mount revanced for 60 seconds, it just puts the rooted apk in the folder and lets us know that its unable to mount system as rw, apk placed here ....try replacing manually?

**Comment by Alprnn357** [comment] 2022-08-17 15:25
I have patched yt and yt music for my rooted device and works flawlessly on mine. Also i used the same android method.
![20220817_181230](https://user-images.githubusercontent.com/37711793/185178278-157667fc-8ad9-4ae4-b387-fcef8dc4edf2.jpg)

**Comment by kevinross** [comment] 2022-08-19 11:33
Can reproduce on my device (rooted OP7 running oxygen os 11), same `/etc/fstab` issue as well.

**Comment by erenmetesar** [comment] 2022-08-20 01:27
It works fine, you just need to install the stock youtube app first and then run the patch. I was having the same issue and solved it this way. Make sure both stock and revanced youtube app versions match.

**Comment by binoysankar** [comment] 2022-08-20 05:00
> It works fine, you just need to install the stock youtube app first and then run the patch. I was having the same issue and solved it this way. Make sure both stock and revanced youtube app versions match.

This resolved my issue. Thank you.

**Comment by reisxd** [comment] 2022-08-20 06:15
> > It works fine, you just need to install the stock youtube app first and then run the patch. I was having the same issue and solved it this way. Make sure both stock and revanced youtube app versions match.
> 
> This resolved my issue. Thank you.

Then I'm closing and pinning this issue for future reference.

**Closed by reisxd** 2022-08-20 06:15 UTC
