### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by GoodLucky777** [reisxd/revanced-builder#465] opened 2022-09-26 07:10 UTC
**Describe the bug**
Build failure during patching.

**To Reproduce**

1. Install revanced builder.
2. Try to patch YouTube.
3. You can see the error.

**Log**
```
Failure
[builder] An error occured:
TypeError: Cannot read properties of null (reading 'replace')
at downloadApp (/data/data/com.termux/files/home/revanced-builder/utils/downloadApp.js:12:39)
at downloadApp (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:31:36)
at getAppVersion (/data/data/com.termux/files/home/revanced-builder/wsEvents/getAppVersion.js:116:14)
at async WebSocket.
```

**revanced-builder Version:** 0e8abff90a7b3f04413e19a594c4779416dc1d39

**Device:**

- OS: Android
- Version: 9

**Additional context**
-

**Comment by d-l-n** [comment] 2022-09-27 00:21
Same on Windows non-root building, lastest builder version

![image](https://user-images.githubusercontent.com/56566724/192403337-40a9572d-aba3-473c-a9b6-5b240ce40136.png)

**Comment by reisxd** [comment] 2022-09-27 05:54
Woops, wrong issue!

**Comment by reisxd** [comment] 2022-09-27 06:25
So, do you have the app you want to patch installed on your device? If so, what's it's version? Did you give Termux root permission?

**Comment by GoodLucky777** [comment] 2022-09-27 09:53
> So, do you have the app you want to patch installed on your device? If so, what's it's version? Did you give Termux root permission?

I tried to patch YouTube v17.37.35 from APKMirror. Yes, I rooted my device with Magisk and grant the permission to it.

**Comment by reisxd** [comment] 2022-09-27 10:00
> > So, do you have the app you want to patch installed on your device? If so, what's it's version? Did you give Termux root permission?
> 
> I tried to patch YouTube v17.37.35 from APKMirror. Yes, I rooted my device with Magisk and grant the permission to it.

Could you try running these:
```bash
cd revanced-builder
node
```

and run this script inside the node REPL:
```js
const { getAppVersion } = require('./utils/getAppVersion.js');
(async() => {
    const ver = getAppVersion('com.google.android.youtube', null, false);
    console.log('Version:', ver);
});
```

and send the output here?

**Comment by GoodLucky777** [comment] 2022-09-27 11:55
```
~/revanced-builder $ node
Welcome to Node.js v16.16.0.
Type ".help" for more information.
> const { getAppVersion } = require('./utils/getAppVersion.js');(async() => {
...     const ver = getAppVersion('com.google.android.youtube', null, false);
...     console.log('Version:', ver);
... });
[AsyncFunction (anonymous)]
>
```

**Comment by reisxd** [comment] 2022-09-27 11:56
> ```
> ~/revanced-builder $ node
> Welcome to Node.js v16.16.0.
> Type ".help" for more information.
> > const { getAppVersion } = require('./utils/getAppVersion.js');(async() => {
> ...     const ver = getAppVersion('com.google.android.youtube', null, false);
> ...     console.log('Version:', ver);
> ... });
> [AsyncFunction (anonymous)]
> >
> ```

Woops, forgot this!

```js
(async() => {
    const ver = getAppVersion('com.google.android.youtube', null, false);
    console.log('Version:', ver);
})();
```

**Comment by GoodLucky777** [comment] 2022-09-27 12:19
```
~/revanced-builder $ node
Welcome to Node.js v16.16.0.
Type ".help" for more information.
> const { getAppVersion } = require('./utils/getAppVersion.js');(async() => {
...     const ver = getAppVersion('com.google.android.youtube', null, false);
...     console.log('Version:', ver);
... })();
Version: Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 35,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
Promise {
  undefined,
  [Symbol(async_id_symbol)]: 34,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
>
```

**Comment by reisxd** [comment] 2022-09-27 12:27
> ```
> ~/revanced-builder $ node
> Welcome to Node.js v16.16.0.
> Type ".help" for more information.
> > const { getAppVersion } = require('./utils/getAppVersion.js');(async() => {
> ...     const ver = getAppVersion('com.google.android.youtube', null, false);
> ...     console.log('Version:', ver);
> ... })();
> Version: Promise {
>   <pending>,
>   [Symbol(async_id_symbol)]: 35,
>   [Symbol(trigger_async_id_symbol)]: 5,
>   [Symbol(destroyed)]: { destroyed: false }
> }
> Promise {
>   undefined,
>   [Symbol(async_id_symbol)]: 34,
>   [Symbol(trigger_async_id_symbol)]: 5,
>   [Symbol(destroyed)]: { destroyed: false }
> }
> >
> ```

And again 😑:
```
(async() => {
    const ver = await getAppVersion('com.google.android.youtube', null, false);
    console.log('Version:', ver);
})();
```

**Comment by GoodLucky777** [comment] 2022-09-27 13:12
```
~/revanced-builder $ node
Welcome to Node.js v16.16.0.
Type ".help" for more information.
> const { getAppVersion } = require('./utils/getAppVersion.js');(async() => {
...     const ver = await getAppVersion('com.google.android.youtube', null, false);
...     console.log('Version:', ver);
... })();
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 32,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> Version: null
>
```

**Comment by shrihanDev** [comment] 2022-09-27 13:53
The last output is reproducible here as well.

**Comment by reisxd** [comment] 2022-09-27 13:55
> The last output is reproducible here as well.

Weird, can you check if it's because of an error or because RegEx couldn't match the output?

**Comment by shrihanDev** [comment] 2022-09-27 14:12
> > The last output is reproducible here as well.
> 
> Weird, can you check if it's because of an error or because RegEx couldn't match the output?

Okay

**Comment by shrihanDev** [comment] 2022-09-27 14:23
So uh, if the device isn't rooted, it throws an exception which is caught and instead of doing something, it simply returns null.

Lemme try on a rooted device.

**Comment by reisxd** [comment] 2022-09-27 14:26
> So uh, if the device isn't rooted, it throws an exception which is caught and instead of doing something, it simply returns null.
> 
> Lemme try on a rooted device.

OP is using an rooted device. (smh shrihan)

**Comment by shrihanDev** [comment] 2022-09-27 14:43
So, tried on a rooted device and it does return the version. Denying root returns `null`. Same when deleted YouTube.

> smh shrihan

I'm mad.

**Comment by reisxd** [comment] 2022-09-27 15:15
> So, tried on a rooted device and it does return the version. Denying root returns `null`. Same when deleted YouTube.
> 
> > smh shrihan
> 
> I'm crazy.

So, I assume even though OP did give Termux root access, it just fails for some reason. If it wasn't installed then it'd throw an user friendly error. @GoodLucky777 could you run `su -c dumpsys package com.google.android.youtube`?

**Comment by shrihanDev** [comment] 2022-09-27 15:26
@GoodLucky777 Can you `console.log` the exception in `utils/getAppVersion.js`?

In lines 31-33:
```js
} catch(e) {
  console.log(e); // THIS LINE
  return null;
}
```

**Comment by GoodLucky777** [comment] 2022-09-27 15:53
I don't install YouTube in my device, is this causing `null` problem?

```
Dexopt state:
  Unable to find package: com.google.android.youtube

Compiler stats:
  Unable to find package: com.google.android.youtube
```

**Comment by reisxd** [comment] 2022-09-27 15:55
> I don't install YouTube in my device, is this causing `null` problem?
> 
> ```
> Dexopt state:
>   Unable to find package: com.google.android.youtube
> 
> Compiler stats:
>   Unable to find package: com.google.android.youtube
> ```

Yep, you need to install it. I should make the catch part also throw an user friendly error.

**Comment by shrihanDev** [comment] 2022-09-27 15:58
> > I don't install YouTube in my device, is this causing `null` problem?
> > 
> > ```
> > Dexopt state:
> >   Unable to find package: com.google.android.youtube
> > 
> > Compiler stats:
> >   Unable to find package: com.google.android.youtube
> > ```
> 
> Yep, you need to install it. I should make the catch part also throw an user friendly error.

Smh Reis smh

**Comment by reisxd** [comment] 2022-09-27 16:23
> > > I don't install YouTube in my device, is this causing `null` problem?
> > > 
> > > ```
> > > Dexopt state:
> > >   Unable to find package: com.google.android.youtube
> > > 
> > > Compiler stats:
> > >   Unable to find package: com.google.android.youtube
> > > ```
> > 
> > Yep, you need to install it. I should make the catch part also throw an user friendly error.
> 
> Smh Reis smh

Come on, I never knew this'd be the fault.

**Comment by shrihanDev** [comment] 2022-09-28 01:50
Closing as invalid.

**Closed by shrihanDev** 2022-09-28 01:50 UTC
