### ISSUE TITLE
Bug From revanced builder on android

### ISSUE THREAD

**Issue by Aperson-12** [reisxd/revanced-builder#503] opened 2022-10-08 07:46 UTC
On the last step of building it happens and the patch process ended

**To Reproduce**
Use termux and build root patched revanced YouTube it's that easy

**Screenshots**
![Screenshot_20221008-140802_Brave](https://user-images.githubusercontent.com/112310438/194696273-557e5adf-bbf6-44e1-8bcf-1ae6170ca50a.png)

**revanced-builder Version:** 
v3.4.15

**Desktop (please complete the following information):**

- OS: Android custom ROM pixel experience 
- Version: Android 12

**Additional context**
If happened on older versions too

**Comment by shrihanDev** [comment] 2022-10-08 07:47
Duplicate of #443 (issue is being tracked there)

**Closed by shrihanDev** 2022-10-08 07:47 UTC
