### ISSUE TITLE
Patching Error While Patching Any Version Of Youtube 

### ISSUE THREAD

**Issue by Tronak007** [reisxd/revanced-builder#603] opened 2022-12-16 15:04 UTC
**Describe the bug**
I Followed All Steps And Tried Patching Recommended Version Of Youtube But The Patcher SaysAs Mention Below

builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/data/ContextKt at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch$Companion.walkMutable(WideSearchbarPatch.kt:48) at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch.execute(WideSearchbarPatch.kt:89) at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch.execute(WideSearchbarPatch.kt:27) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.data.ContextKt at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ... 20 more

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [v3.6.1

Using On Android With Latest Turmex Application 

**Additional context**
![Screenshot_20221216-203100](https://user-images.githubusercontent.com/106589892/208126537-e86e2daa-a67b-4e2a-9222-060f913b3e45.png)

**Comment by reisxd** [comment] 2022-12-16 15:17
Dupe of #593.

**Closed by reisxd** 2022-12-16 15:17 UTC
