### ISSUE TITLE
Downloading Reddit 2022.35.1 fails as only bundle download is available

### ISSUE THREAD

**Issue by caneleex** [reisxd/revanced-builder#457] opened 2022-09-23 20:56 UTC
**Describe the bug**
Downloading Reddit `2022.35.1` fails with this error:
```
[builder] An error occured.
FetchError: request to https://www.apkmirror.comundefined/ failed, reason: getaddrinfo ENOTFOUND www.apkmirror.comundefined
    at ClientRequest.<anonymous> (C:\snapshot\revanced-builder\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```

**To Reproduce**

1. Start Patching
2. Choose the Reddit app in the App Selector
3. Keep clicking the "Continue" button until you get to the list of patches
4. Choose any patch, it doesn't matter
5. Select version `2022.35.1`
6. Click on "Continue"
7. Observe

**Screenshots**

![](https://i.imgur.com/VEg70mB.png)

**revanced-builder Version:** v3.4.7

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
I suspect this happens because there's only bundle download available, no `.apk` download. Downloading `2022.35.0` works just fine.

See https://www.apkmirror.com/apk/redditinc/reddit/reddit-2022-35-1-release/

**Comment by reisxd** [comment] 2022-09-24 04:36
Dupe of #450.

**Closed by reisxd** 2022-09-24 04:36 UTC
