### ISSUE TITLE
Patching YouTube fails with "cp: cannot create regular file ReVanced YouTube apk: operation not permitted" error message

### ISSUE THREAD

**Issue by daygumon** [reisxd/revanced-builder#558] opened 2022-11-18 03:21 UTC
**Describe the bug**
Using Revanced builder browser version opened by Termux on Android, the patching YouTube process fails with the screenshotted error message. The instructions say to report the bug here.

**To Reproduce**
0. Uninstall YouTube app updates
1. Install F-Droid
2. Install Termux using F-Droid
3. Open Termux
4. Run ``curl -sLo revanced-builder.sh https://raw.githubusercontent.com/reisxd/revanced-builder/main/android-interface.sh
chmod +x revanced-builder.sh
./revanced-builder.sh``
5. Select "YouTube" as app to patch and continue
6. Select all patches to include and continue
7. Select "17.45.34" as version to download and continue
8. Some patches have error messages, but most suceed. Eventually it fails with the error message.

**Screenshots**
![Screenshot_20221117_202751_Firefox Nightly](https://user-images.githubusercontent.com/112282717/202596193-691a103a-6ead-45f9-87fd-3b1d3fd57ad4.jpg)
```
[builder] Listening at port 8001
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: Command failed: cp /data/data/com.termux/files/home/revanced-builder/revanced/ReVanced-YouTube-v17.45.34-arm64-v8a-cli_v2.15.0-patches_v2.111.0.apk /storage/emulated/0/ReVanced-YouTube-v17.45.34-arm64-v8a-cli_v2.15.0-patches_v2.111.0.apk
cp: cannot create regular file '/storage/emulated/0/ReVanced-YouTube-v17.45.34-arm64-v8a-cli_v2.15.0-patches_v2.111.0.apk': Operation not permitted

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

```

**revanced-builder Version:**
v3.5.0

**Additional context**

**Comment by reisxd** [comment] 2022-11-18 08:00
Dupe of #234.

**Closed by reisxd** 2022-11-18 08:00 UTC

**Comment by daygumon** [comment] 2022-11-18 16:28
Thank you. Your `termux-setup-storage` solution worked.
