### ISSUE TITLE
seekbar-tapping patch failed on Linux

### ISSUE THREAD

**Issue by Not-James-Bond** [reisxd/revanced-builder#452] opened 2022-09-23 11:15 UTC
**Describe the bug**
While building got an seekbar-tapping failed and then stuck at installing phase.

**To Reproduce**
Run the builder for rooted device with YT (ver 17.36.37) and select all patches excluding 2 non rooted patches and debugging patch.

**Screenshots**
[Hastebin](https://hastebin.com/nakuyigone.sql)
```
[builder] SEVERE: seekbar-tapping failed:
[builder] app.revanced.patcher.patch.PatchResultError: Could not find the correct register
[builder] at app.revanced.patches.youtube.interaction.seekbar.patch.EnableSeekbarTappingPatch.execute(EnableSeekbarTappingPatch.kt:86) at app.revanced.patches.youtube.interaction.seekbar.patch.EnableSeekbarTappingPatch.execute(EnableSeekbarTappingPatch.kt:27)
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)

```
![image](https://user-images.githubusercontent.com/32868290/191948742-eb5356e7-db2c-4a70-b965-b77d5ef632af.png)

**revanced-builder Version:**
v3.4.7

***Info about packages***
>revanced-patches-v2.68.2
>revanced-cli-v2.11.2

**Desktop (please complete the following information):**

- OS: Linux
- Version: Manjaro

**Additional context**
Tried twice and stuck at installing phase twice.

**Comment by Not-James-Bond** [comment] 2022-09-23 11:37
I Tried to install again after cleaning and redownloading the tool. This time i got it installed but got the same seekbar falied.
New error which I got was 
![Cleanup Error](https://user-images.githubusercontent.com/32868290/191952068-c959645e-aeae-4c16-8f06-6dea6b45a180.png)
![Screenshot](https://user-images.githubusercontent.com/32868290/191952195-19a6c2b6-20a5-43f4-9e0e-8cd973e8a6ab.png)

**Comment by reisxd** [comment] 2022-09-23 13:14
Not an issue with Builder and dupe of #449.

**Closed by reisxd** 2022-09-23 13:14 UTC
