### ISSUE TITLE
Windows builder :failure

### ISSUE THREAD

**Issue by mooms06** [reisxd/revanced-builder#470] opened 2022-09-27 00:34 UTC
**Describe the bug**
After running the builder on recommended version (17.36.37), I have the following message:

[builder] An error occured:
TypeError: Cannot read properties of undefined (reading 'replace')
at outputName (C:\snapshot\revanced-builder\wsEvents\patchApp.js:130:5)
at afterBuild (C:\snapshot\revanced-builder\wsEvents\patchApp.js:39:3)
at Socket. (C:\snapshot\revanced-builder\wsEvents\patchApp.js:212:53)
at Socket.emit (node:events:527:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/25405517/192404316-38126b9f-3615-4299-b247-5430a58c0a8b.png)
Here are the selected patches
![image](https://user-images.githubusercontent.com/25405517/192404636-052ee06a-a484-420d-ac0f-21f8f5d39aa1.png)

**revanced-builder Version 3.4.8

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10 21H2

**Additional context**

**Comment by reisxd** [comment] 2022-09-27 03:51
Dupe of #469.

**Closed by reisxd** 2022-09-27 03:51 UTC
