### ISSUE TITLE
TikTok patch page not working

### ISSUE THREAD

**Issue by Gontier-Julien** [reisxd/revanced-builder#401] opened 2022-09-09 13:52 UTC
**Describe the bug**
The TikTok patch page show no patch at all

**To Reproduce**
Try to patch tiktok

**Screenshots**
![image](https://user-images.githubusercontent.com/52894530/189365602-73d33c21-bad1-4ee7-944f-8efb616bc430.png)

**revanced-builder Version: since v3.4.0 to v3.4.3

**Desktop (please complete the following information):**

- OS: Linux (ArchLinux)

**Additional context**
Error trown out in the terminal

`TypeError: Cannot read properties of undefined (reading 'patches')
    at getPatchesList (/snapshot/revanced-builder/utils/PatchListRememberer.js:50:5)
    at getPatchList (/snapshot/revanced-builder/utils/PatchListRememberer.js:82:17)
    at getPatches (/snapshot/revanced-builder/wsEvents/getPatches.js:23:31)
    at WebSocket.<anonymous> (/snapshot/revanced-builder/index.js:159:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/snapshot/revanced-builder/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/snapshot/revanced-builder/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/snapshot/revanced-builder/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/snapshot/revanced-builder/node_modules/ws/lib/receiver.js:148:22)`

**Comment by reisxd** [comment] 2022-09-09 13:59
Dupe of #358.

**Closed by reisxd** 2022-09-09 13:59 UTC
