### ISSUE TITLE
Failed to patch Youtube and Youtube Music (AndroidManifest.xml not found)

### ISSUE THREAD

**Issue by HynDuf7** [reisxd/revanced-builder#478] opened 2022-09-27 19:00 UTC
**Describe the bug**
Failed patching Youtube and Youtube Music

**To Reproduce**

1. Normal patching.

**Screenshots**
```
 [builder] INFO: Reading dex files
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping hide-premium-navbar, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.spotify.music
[builder] WARNING: Skipping spotify-theme, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.spotify.music
[builder] WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with de.dwd.warnapp
[builder] WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
[builder] WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.twitter.android
[builder] INFO: Skipping compact-header, reason: manually excluded
[builder] WARNING: Skipping swipe-controls, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping downloads, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping seekbar-tapping, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping remember-video-quality, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping custom-playback-speed, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] INFO: Skipping enable-debugging, reason: excluded by default
[builder] WARNING: Skipping minimized-playback, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping client-spoof, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube, com.vanced.android.youtube
[builder] WARNING: Skipping custom-video-buffer, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping settings, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping microg-support, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping hdr-auto-brightness, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping always-autorepeat, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping general-ads, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping hide-infocard-suggestions, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping video-ads, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube WARNING: Skipping hide-time-and-seekbar, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping old-quality-layout, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping enable-wide-searchbar, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping disable-fullscreen-panels, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube WARNING: Skipping hide-autoplay-button, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping premium-heading, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping custom-branding, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping hide-create-button, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping hide-shorts-button, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping theme, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping sponsorblock, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube WARNING: Skipping hide-cast-button, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube WARNING: Skipping tablet-mini-player, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping return-youtube-dislike, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping hide-watermark, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping disable-auto-player-popup-panels, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] WARNING: Skipping disable-auto-captions, reason: incompatible with com.google.android.apps.youtube.music. This patch is only compatible with com.google.android.youtube
[builder] INFO: exclusive-audio-playback succeeded
[builder] INFO: codecs-unlock succeeded
[builder] SEVERE: music-microg-support failed:
[builder] app.revanced.patcher.patch.PatchResultError: 'music-microg-support' depends on 'music-microg-support' but the following error was raised: java.io.FileNotFoundException: ./revanced-cache/AndroidManifest.xml (No such file or directory)
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:259) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:46) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:383) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
[builder] at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFO: music-video-ads succeeded
[builder] INFO: tasteBuilder-remover succeeded
[builder] INFO: minimized-playback-music succeeded
[builder] INFO: upgrade-button-remover succeeded
[builder] INFO: hide-get-premium succeeded
[builder] INFO: background-play succeeded
[builder] INFO: Not compiling resources because resource patching is not required
[builder] INFO: Writing modified dex files
[builder] INFO: Writing dex file classes3.dex
[builder] INFO: Writing dex file classes4.dex
[builder] INFO: Writing dex file classes2.dex
[builder] INFO: Writing dex file classes.dex
[builder] INFO: Aligning revanced_raw.apk to revanced_aligned.apk
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] INFO: Found existing keystore: revanced.keystore
[builder] INFO: Copying revanced_signed.apk to revanced.apk
[builder] INFO: Finished
[builder] Copied files over to /storage/emulated/0/! Please install ReVanced, its located in /storage/emulated/0/ReVanced-YouTube_Music-cli_v2.12.0-patches_v2.69.3.apk and if you are building YT/YTM ReVanced without root, also install /storage/emulated/0/microg.apk.
```

**revanced-builder Version:** latest

**Additional context**
It worked normally a few days ago. There's something about the AndroidManifest.xml file not found.

**Comment by cyberboh** [comment] 2022-09-28 00:36
i get the same, also on android

**Comment by shrihanDev** [comment] 2022-09-28 01:48
Known issue, unfortunately. Closing because duplicate of #474.

**Closed** 2022-09-28 01:48 UTC
