### ISSUE TITLE
Error patching tiktok

### ISSUE THREAD

**Issue by ghazayel** [reisxd/revanced-builder#432] opened 2022-09-16 16:40 UTC
Error showing up while trying to patch "Tiktok"

After "downloading dependencies" has finished I automatically receive this error: 
"TypeError: Cannot read properties of undefined (reading 'patches') at get PatchesList.

![Screenshot_20220916-203520_Brave](https://user-images.githubusercontent.com/8275031/190687654-cadd4917-dd18-4b59-b99a-c46049c8ace1.jpg)

**Comment by reisxd** [comment] 2022-09-16 18:16
Dupe of #358.

**Closed** 2022-09-16 18:16 UTC
