### ISSUE TITLE
TikTok patches not showing up.

### ISSUE THREAD

**Issue by F-AlFaris** [reisxd/revanced-builder#391] opened 2022-09-07 12:33 UTC
**Describe the bug**
TikTok patches not showing up.

**To Reproduce**

Select TikTok
Download dependencies
Click next
Nothing shows up

**revanced-builder Version:** v3.4.3

**Desktop (please complete the following information):**

- OS: Android
- Version: 13

**Comment by reisxd** [comment] 2022-09-07 12:35
Dupe of #358.

**Closed by reisxd** 2022-09-07 12:35 UTC
