### ISSUE TITLE
Builder can't download jar files

### ISSUE THREAD

**Issue by GameGuyOnYT** [reisxd/revanced-builder#304] opened 2022-08-24 11:11 UTC
**Describe the bug**
The builder cannot download the jar files when it comes to the dependencies page.

**To Reproduce**

1. Start the builder
2. Select YouTube
3. See error

**Screenshots**
![IMG_20220824_141044.jpg](https://user-images.githubusercontent.com/81768350/186404325-4ae1aa03-c382-483b-871e-e205571af886.jpg)

**revanced-builder Version:** 3.2.4

**Desktop (please complete the following information):**

- OS: Android
- Version: 11

**Additional context**

**Comment by reisxd** [comment] 2022-08-24 11:12
Dupe of #293

**Closed by reisxd** 2022-08-24 11:12 UTC
