### ISSUE TITLE
Videos don't load.

### ISSUE THREAD

**Issue by TgZ39** [reisxd/revanced-builder#291] opened 2022-08-22 18:56 UTC
**Describe the bug**
The videos do not load when clicking on them
.

**revanced-builder Version:** [3.4.2]

**Desktop (please complete the following information):**

- OS: [Windows]
- Version: [11]

**Comment by reisxd** [comment] 2022-08-22 19:19
Dupe of #290.

**Closed by reisxd** 2022-08-22 19:19 UTC
