### ISSUE TITLE
TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by Ketchup901** [reisxd/revanced-builder#53] opened 2022-07-12 16:03 UTC
I'm on Linux using version 1.2.10.

```
Downloading latest patches, integrations and cli...
[revanced-cli-2.5.3-all.jar] ✓
[revanced-patches-2.13.3.dex] ✓
[revanced-patches-2.13.3.jar] ✓
[app-release-unsigned.apk] ✓
[microg.apk] ✓
An error occured.
TypeError: Cannot read properties of null (reading '0')
    at /snapshot/revanced-builder/index.js:517:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...
```

**Comment by Ketchup901** [comment] 2022-07-12 16:13
Ok, it works when following the instructions in the readme but not when using the executable supplied in the releases tab.

**Comment by reisxd** [comment] 2022-07-12 16:39
Cannot reproduce the error on Android (Termux, it doesn't work on it but it can get the patch descriptions successfully)

**Comment by shrihanDev** [comment] 2022-07-12 16:41
Cannot reproduce on Arch Linux, binary or source.

**Comment by reisxd** [comment] 2022-07-13 04:56
Closing because couldn't reproduce.

**Closed by reisxd** 2022-07-13 04:56 UTC
