### ISSUE TITLE
Can't build anything besides YT and YT Music

### ISSUE THREAD

**Issue by furopi** [reisxd/revanced-builder#562] opened 2022-11-18 23:36 UTC
Dear Sir or Madam,

I get the following error shown in the log excerpt below when I try building somehting else thank YT or YT Music Vanced. I tried lot's of java heap size modification, I even set up deafult heap size to a tremendously huge amount, resukt: problem remains. Please help, as I want to build and use the the other APK's.

Thank you and kind regards,
Florian

[builder] INFORMATION: Skipping compact-header, reason: excluded by default
[builder] WARNUNG: Skipping upgrade-button-remover, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNUNG: Skipping music-video-ads, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNUNG: Skipping background-play, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNUNG: Skipping exclusive-audio-playback, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNUNG: Skipping codecs-unlock, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNUNG: Skipping music-microg-support, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNUNG: Skipping unlock-pro, reason: incompatible with com.reddit.frontpage. This patch is only compatible with com.awedea.nyx
[builder] INFORMATION: premium-icon-reddit succeeded
[builder] INFORMATION: general-reddit-ads succeeded
[builder] INFORMATION: Not compiling resources because resource patching is not required
[builder] INFORMATION: Writing modified dex files
[builder] Exception in thread "main"
[builder] java.lang.OutOfMemoryError: Java heap space

**Comment by reisxd** [comment] 2022-11-19 05:09
Dupe of #137.

**Closed by reisxd** 2022-11-19 05:09 UTC
