### ISSUE TITLE
Youtube build failed, what can I do?

### ISSUE THREAD

**Issue by Lagger006** [reisxd/revanced-builder#720] opened 2023-04-27 09:11 UTC
**Describe the bug**
I got this error while i use the app 

 An error occured:Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENTat ChildProcess._handle.onexit (node:internal/child_process:283:19)at onErrorNT (node:internal/child_process:476:16)at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

I saw some ppl say that we should use the revanced-signed.apk but it didn't work for non-root since the apk try to update the Youtube and not install as a new app.

I tried the older versions but 3.8.0 and 3.9.0 say that I need to install adb even if that is optional and only used for rooted phones.

**Screenshots**
![image](https://user-images.githubusercontent.com/107367141/234814241-ec72cb67-5f09-4fab-9e28-478234034e71.png)

**revanced-builder Version: 3.9.1**

**Desktop (please complete the following information):**

- OS: Win10

**Additional context**

**Comment by wenger69** [comment] 2023-04-27 10:29
I got the same issues on windows 11 x64!

**Comment by mooms06** [comment] 2023-04-28 12:32
Duplicate of https://github.com/reisxd/revanced-builder/issues/700

Next time please search before opening an issue.

**Closed** 2023-04-30 05:09 UTC
