### ISSUE TITLE
'"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"' mount: bad /etc/fstab: No such file or directory

### ISSUE THREAD

**Issue by warmoans** [reisxd/revanced-builder#215] opened 2022-08-10 19:32 UTC
An error occured.
Error: Command failed: su -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'
mount: bad /etc/fstab: No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues

Using:
Pixel 6 Pro Stock A12.1 Magisk 25.2

**Comment by reisxd** [comment] 2022-08-10 19:47
Dupe of #213

**Closed by reisxd** 2022-08-10 19:47 UTC
