### ISSUE TITLE
Failed to load available twitch APK version list.

### ISSUE THREAD

**Issue by GitMolHub** [reisxd/revanced-builder#640] opened 2023-01-13 01:04 UTC
![Screenshot_20230112-195945](https://user-images.githubusercontent.com/114028995/212213031-9483059e-3dc2-45e2-8728-815d8b5e099d.png)

I get this error when I try to pull up the list of versions of the twitch APK to patch and I got this error.

**Comment by JustOptimize** [comment] 2023-04-07 17:38
Duplicate of #638

**Closed** 2023-04-07 19:54 UTC
