### ISSUE TITLE
KotlinReflectionNotSupportedError when patching anything

### ISSUE THREAD

**Issue by Auncaughbove17** [reisxd/revanced-builder#589] opened 2022-12-15 13:56 UTC
**Describe the bug**
Trying to patch anything returns this error:
```
 [builder] Exception in thread "main"
[builder] kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:88) at kotlin.jvm.internal.ClassReference.getNestedClasses(ClassReference.kt:24) at kotlin.reflect.full.KClasses.getCompanionObject(KClasses.kt:47) at app.revanced.patcher.extensions.PatchExtensions.getOptions(AnnotationExtensions.kt:62) at app.revanced.utils.OptionsLoader.generateDefaults(OptionsLoader.kt:68) at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:25) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137) at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
[builder] at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)

```

**To Reproduce**
```bash
git clone https://github.com/reisxd/revanced-builder/
cd revanced-builder
docker-compose up
```
afterwards open localhost:8000 and try to patch anything

**Screenshots**
![image](https://user-images.githubusercontent.com/26165288/207876321-d43eb2f3-7a23-4b2f-bd55-1af4b125abbb.png)

**revanced-builder Version:** 3.5.0

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
I'm using Docker in Ubuntu WSL2.
I also just tested downloading the source zip from the last release instead of using git clone. Same issue.

**Comment by reisxd** [comment] 2022-12-15 14:15
Not an issue with Builder. Dupe of #588.

**Closed by reisxd** 2022-12-15 14:15 UTC

**Comment by Auncaughbove17** [comment] 2022-12-15 14:22
@reisxd with what is the issue then? It seems I'm by far not the only one with the issue. I would like to try and fix this.

**Comment by Auncaughbove17** [comment] 2022-12-15 16:07
Ah, so it's just that way more people use this tool than revanced-cli directly, which is why there was no issue there :D
Thanks for the info.
