### ISSUE TITLE
Error install youtube revanced

### ISSUE THREAD

**Issue by carls677** [reisxd/revanced-builder#405] opened 2022-09-10 18:32 UTC
![IMG_20220910_123105_956](https://user-images.githubusercontent.com/28660956/189497002-868bf321-d9be-40b9-91f9-b333f81427a1.jpg)

it won't let me install any version

**Comment by reisxd** [comment] 2022-09-10 18:41
Dupe of #272

**Closed by reisxd** 2022-09-10 18:41 UTC
