### ISSUE TITLE
error while exiting (running in docker)

### ISSUE THREAD

**Issue by vo1d-7bin** [reisxd/revanced-builder#456] opened 2022-09-23 18:59 UTC
![image](https://user-images.githubusercontent.com/100482403/192037764-4e1c4485-74dd-4324-a4b4-956db422ce2e.png)
logs of the server 
![image](https://user-images.githubusercontent.com/100482403/192037828-6d0cf361-1324-4fb2-b4c9-4f86ffd5ad99.png)
using  a Ubuntu server can be checked [here](https://revanced.vo1d.cf/failure/?error=An%20error%20occured%3A%0ATypeError%3A%20Invalid%20host%20defined%20options%0A%20%20%20%20at%20cleanExit%20(%2Fsnapshot%2Frevanced-builder%2Findex.js%3A92%3A14)%0A%20%20%20%20at%20process.%3Canonymous%3E%20(%2Fsnapshot%2Frevanced-builder%2Findex.js%3A150%3A29)%0A%20%20%20%20at%20process.emit%20(node%3Aevents%3A527%3A28)%0APlease%20report%20this%20bug%20here%3A%20https%3A%2F%2Fgithub.com%2Freisxd%2Frevanced-builder%2Fissues.)

**Comment by reisxd** [comment] 2022-09-23 19:34
Dupe of #449.

**Closed by reisxd** 2022-09-23 19:34 UTC
