### ISSUE TITLE
Builder not able to integrate hide-shorts properly

### ISSUE THREAD

**Issue by Ansh4011** [reisxd/revanced-builder#529] opened 2022-10-27 17:36 UTC
**Describe the bug**
Revanced-builder is not able to integrate the `hide-shorts-button` patch properly, as soon as the built app is launched it crashes. 

**To Reproduce**

1. Get the latest revanced-patches and other files. Apparent version of patch = v2.92.2
2. Build yt revanced (v17.36.37) and do include the `hide-shorts-button` patch.
3. Install it, and it won't launch (atleast it doesn't launch for me and few others too)

**Revanced-Builder Version:** 
v3.4.15

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Comment by Ansh4011** [comment] 2022-10-27 17:36
Ig it's about time we need a new release of Revanced-Builder!

**Comment by anxiouslelimo** [comment] 2022-10-27 18:06
Similar issue here.
Used both hide-shorts-button and hide-create-button. It works. But after login with microg it crashed. Excluded hide-create-button. Now it works even with microg login.  I havent tried excluding hide-shorts-button. 

I was wondering if you have the hide-create-button included in build. 



> **Describe the bug** Revanced-builder is not able to integrate the `hide-shorts-button` patch properly, as soon as the built app is launched it crashes.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Get the latest revanced-patches and other files. Apparent version of patch = v2.92.2
> 2. Build yt revanced (v17.36.37) and do include the `hide-shorts-button` patch.
> 3. Install it, and it won't launch (atleast it doesn't launch for me and few others too)
> 
> **Revanced-Builder Version:** v3.4.15
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Version: 10

**Comment by Ansh4011** [comment] 2022-10-27 19:11
Yeah I do have the `hide-create-button` patch included. Excluding the `hide-shorts-button` made it work for me, but I just don't like to have that clutter over there, so I'll instead wait till the builder get's fixed. The last properly working patch was `v2.83.2`, in case you wanted to know.

**Comment by reisxd** [comment] 2022-10-28 03:57
Dupe of #525. 


Again, these issues were **NEVER** a Builder issue, but only patch issues. The reason why Builder doesn't get updates is because there's no reason to. It still works, and there'll be only updates when PatchOptions finally gets implemented properly / Split support finally gets implemented.

**Closed by reisxd** 2022-10-28 03:57 UTC

**Comment by Ansh4011** [comment] 2022-10-28 04:44
Alright. Love the builder btw!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
