### ISSUE TITLE
Error on 32bit phone

### ISSUE THREAD

**Issue by Yastik** [reisxd/revanced-builder#108] opened 2022-07-30 13:06 UTC
**Describe the bug**
Copying ReVanced and MicroG to phones storage...
An error occured.
Error: Command failed: cp revanced/revanced.apk /storage/emulated/0/revanced.apk
cp: cannot stat 'revanced/revanced.apk': No such file or directory

   at ChildProcess.exithandler (node:child_process:398:12)
   at ChildProcess.emit (node:events:527:28)
   at maybeClose (node:internal/child_process:1092:16)
   at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'cp revanced/revanced.apk /storage/emulated/0/revanced.apk',
  stdout: '',
  stderr: "cp: cannot 
Please make an issue at https://github.com/reisxd/revanced-builder/issues.
Press any key to exit...

**To Reproduce**

1. Select the latest youtube version or the play store version

**revanced-builder Version:** 2.1.2

- OS: 32bit android
- Version: 10

**Additional context**
I was able to build youtube music with no problems i also tried both the "latest" youtube version and the latest google play version (17.28.34)

**Comment by reisxd** [comment] 2022-07-31 04:16
Hey, can you try building again?

**Comment by Yastik** [comment] 2022-07-31 17:49
I got the same error

**Comment by reisxd** [comment] 2022-07-31 19:27
> I got the same error

Can you try running this:
```
cd revanced-builder-cli
java -jar ./revanced/revanced-cli-2.8.0-all.jar -b ./revanced/revanced-patches-2.28.0.jar --custom-aapt2-binary revanced/aapt2 -t ./revanced-cache --experimental -a ./revanced/youtube.apk  -o ./revanced/revanced.apk  -m ./revanced/app-release-unsigned.apk  -i swipe-controls -i seekbar-tapping -i minimized-playback -i amoled -i disable-create-button -i hide-cast-button -i return-youtube-dislike -i hide-autoplay-button -i premium-heading -i custom-branding -i disable-fullscreen-panels -i old-quality-layout -i hide-shorts-button -i hide-watermark -i sponsorblock -i enable-wide-searchbar -i force-vp9-codec -i custom-video-buffer -i always-autorepeat -i microg-support -i settings -i enable-debugging -i custom-playback-speed -i hdr-auto-brightness -i remember-video-quality -i video-ads -i general-ads
```

**Comment by Yastik** [comment] 2022-07-31 19:56
> > I got the same error
> 
> Can you try running this:
> 
> ```
> cd revanced-builder-cli
> java -jar ./revanced/revanced-cli-2.8.0-all.jar -b ./revanced/revanced-patches-2.28.0.jar --custom-aapt2-binary revanced/aapt2 -t ./revanced-cache --experimental -a ./revanced/youtube.apk  -o ./revanced/revanced.apk  -m ./revanced/app-release-unsigned.apk  -i swipe-controls -i seekbar-tapping -i minimized-playback -i amoled -i disable-create-button -i hide-cast-button -i return-youtube-dislike -i hide-autoplay-button -i premium-heading -i custom-branding -i disable-fullscreen-panels -i old-quality-layout -i hide-shorts-button -i hide-watermark -i sponsorblock -i enable-wide-searchbar -i force-vp9-codec -i custom-video-buffer -i always-autorepeat -i microg-support -i settings -i enable-debugging -i custom-playback-speed -i hdr-auto-brightness -i remember-video-quality -i video-ads -i general-ads
> ```

WARNING: Skipping timeline-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
WARNING: Skipping general-reddit-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
WARNING: Skipping minimized-playback-music: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping hide-get-premium: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping compact-header: Not explicitly included
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-microg-support: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-video-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping enable-debugging: Not explicitly included
INFO: swipe-controls succeeded
INFO: seekbar-tapping succeeded
INFO: minimized-playback succeeded
INFO: amoled succeeded
INFO: disable-create-button succeeded
INFO: hide-cast-button succeeded
INFO: return-youtube-dislike succeeded
INFO: hide-autoplay-button succeeded
INFO: premium-heading succeeded
INFO: custom-branding succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
INFO: hide-shorts-button succeeded
INFO: hide-watermark succeeded
INFO: sponsorblock succeeded
INFO: enable-wide-searchbar succeeded
INFO: force-vp9-codec succeeded
INFO: custom-video-buffer succeeded
INFO: always-autorepeat succeeded
INFO: microg-support succeeded
INFO: settings succeeded
INFO: custom-playback-speed succeeded
INFO: hdr-auto-brightness succeeded
INFO: remember-video-quality succeeded
INFO: video-ads succeeded
INFO: general-ads succeeded
INFO: hide-infocard-suggestions succeeded
INFO: Compiling resources
WARNING: aapt2 W 07-31 22:53:04 13247 13247] Unknown chunk type '200'.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [revanced/aapt2, link, -o, /data/data/com.termux/files/home/storage/revanced-builder-cli/./revanced-cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530516928, --version-name, 17.28.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL6476093838457595998.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/storage/revanced-builder-cli/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/storage/revanced-builder-cli/./revanced-cache/build/resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:199)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [revanced/aapt2, link, -o, /data/data/com.termux/files/home/storage/revanced-builder-cli/./revanced-cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530516928, --version-name, 17.28.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL6476093838457595998.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/storage/revanced-builder-cli/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/storage/revanced-builder-cli/./revanced-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more

**Comment by reisxd** [comment] 2022-08-02 13:12
I cannot reproduce the issue on my armv7 (arm32) tablet. Closing the issue.

**Closed** 2022-08-02 13:12 UTC
