### ISSUE TITLE
Error when patching

### ISSUE THREAD

**Issue by TgZ39** [reisxd/revanced-builder#497] opened 2022-10-06 04:42 UTC
**Describe the bug**
Some error

**To Reproduce**
start patching latest stable

**Screenshots**

**revanced-builder Version:** [latest]

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Version: [11]

**Additional context**
This is the error:
[builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[builder] at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[builder] at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
[builder] at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[builder] at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[builder] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ... 22 more

**Comment by 0xShadx0** [comment] 2022-10-06 05:00
Can confirm same error reproduced myself just now.

**Comment by reisxd** [comment] 2022-10-06 05:05
Dupe of #496.

**Closed by reisxd** 2022-10-06 05:05 UTC
