### ISSUE TITLE
Error when trying to patch

### ISSUE THREAD

**Issue by EnolaGae** [reisxd/revanced-builder#591] opened 2022-12-15 17:20 UTC
Hello, I've been trying to get the builder to work on my ubuntu machine but I seem to run into issues, I get this error on the console side whenever I try to patch the youtube APK:
```
revanced-builder    | [builder] Listening at port 8000
revanced-builder    | [builder] The webserver is now running at http://localhost:8000
revanced-builder    | [builder] An error occured.
revanced-builder    | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
revanced-builder    |     at new NodeError (node:internal/errors:393:5)
revanced-builder    |     at validateString (node:internal/validators:163:11)
revanced-builder    |     at join (node:path:1172:7)
revanced-builder    |     at patchApp (/app/revanced-builder/wsEvents/patchApp.js:154:8)
revanced-builder    |     at WebSocket.<anonymous> (/app/revanced-builder/index.js:194:15)
revanced-builder    |     at WebSocket.emit (node:events:513:28)
revanced-builder    |     at Receiver.receiverOnMessage (/app/revanced-builder/node_modules/ws/lib/websocket.js:1178:20)
revanced-builder    |     at Receiver.emit (node:events:513:28)
revanced-builder    |     at Receiver.dataMessage (/app/revanced-builder/node_modules/ws/lib/receiver.js:528:14)
revanced-builder    |     at Receiver.getData (/app/revanced-builder/node_modules/ws/lib/receiver.js:446:17)
revanced-builder    | [builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```
And on the builder I get this output:
```
[builder] Exception in thread "main"
[builder] kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
[builder] at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:88)
[builder] at kotlin.jvm.internal.ClassReference.getNestedClasses(ClassReference.kt:24)
[builder] at kotlin.reflect.full.KClasses.getCompanionObject(KClasses.kt:47)
[builder] at app.revanced.patcher.extensions.PatchExtensions.getOptions(AnnotationExtensions.kt:62)
[builder] at app.revanced.utils.OptionsLoader.generateDefaults(OptionsLoader.kt:68)
[builder] at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:25)
[builder] at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137)
[builder] at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
[builder] at picocli.CommandLine.access$1500(CommandLine.java:148)
[builder] at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
[builder] at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
```
I've seen a few people asking about the Kotlin Reflection issue, and I'm honestly not too sure how to fix it... Sorry if this is not the right place to ask. Thanks in advance :)

**Comment by reisxd** [comment] 2022-12-15 17:23
Not an issue with Builder. Dupe of #588.

**Comment by EnolaGae** [comment] 2022-12-15 17:23
Okay, reported due to it asking me too honestly, thanks for the quick answer :)

**Closed by reisxd** 2022-12-15 17:23 UTC
