### ISSUE TITLE
Error when trying to download after patching

### ISSUE THREAD

**Issue by JonLit** [reisxd/revanced-builder#240] opened 2022-08-15 22:18 UTC
Hi, 
when clicking the Download button after the build has completed, a new Tab opens, with the address of `http://localhost:8000/revanced.apk`
The site contains this:
`Error: File or directory '/**/revanced-builder/revanced/ReVanced-Twitter-v9.54.0-release.0-cli_2.9.3-patches_2.37.0.apk' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at findNativeAddonForStat (pkg/prelude/bootstrap.js:1448:32)
    at statFromSnapshot (pkg/prelude/bootstrap.js:1471:25)
    at Object.stat (pkg/prelude/bootstrap.js:1497:5)
    at SendStream.sendFile (/snapshot/revanced-builder/node_modules/send/index.js:717:6)
    at SendStream.pipe (/snapshot/revanced-builder/node_modules/send/index.js:591:8)
    at sendfile (/snapshot/revanced-builder/node_modules/express/lib/response.js:1130:8)
    at ServerResponse.sendFile (/snapshot/revanced-builder/node_modules/express/lib/response.js:449:3)
    at ServerResponse.download (/snapshot/revanced-builder/node_modules/express/lib/response.js:598:15)
    at /snapshot/revanced-builder/index.js:25:7`

Using 
revanced-builder v3.2.0, 
openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9)
OpenJDK 64-Bit Server VM (build 18.0.2+9, mixed mode)
on Garuda Linux

**Comment by reisxd** [comment] 2022-08-16 04:09
Dupe of #224.

**Closed by reisxd** 2022-08-16 04:09 UTC
