### ISSUE TITLE
Error: Make sure you have kotlin-reflect.jar in the classpath

### ISSUE THREAD

**Issue by aDifferentBook** [reisxd/revanced-builder#590] opened 2022-12-15 14:13 UTC
**Describe the bug**
Unable to patch apk (YouTube) using Termux on Android 12.1, getting error.

`
[builder] Exception in thread "main"
[builder] kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath at
`

**To Reproduce**

1. Update your revanced-builder to latest version using `./revanced-builder.sh update`
2. Run revanced-builder using `./revanced-builder.sh` open browser.
3. Download latest patches.
4. Select YouTube (17.45.36 marked as stable), download apk
5. Wait to start patching process and see the error at first line.

**Screenshots**
![Screenshot_20221215-193004_Firefox.png](https://user-images.githubusercontent.com/80353171/207881802-e111e27c-eac6-4598-aac6-052a70813775.png)

**revanced-builder Version:** 3.5.0

**Additional context**
Not applicable.

**Comment by reisxd** [comment] 2022-12-15 14:15
Not an issue with Builder. Dupe of #588.

**Closed by reisxd** 2022-12-15 14:15 UTC
