### ISSUE TITLE
Revanced Builder won't allow app version selection 

### ISSUE THREAD

**Issue by erenmete** [reisxd/revanced-builder#387] opened 2022-09-06 08:28 UTC
Version selection is bugged, it automatically downloads the latest stable version instead of listing versions

https://user-images.githubusercontent.com/58091473/188585839-376be423-9c14-476d-9ede-6740412fd671.mp4

**Comment by reisxd** [comment] 2022-09-06 08:35
Dupe of #368.

**Closed by reisxd** 2022-09-06 08:35 UTC
