### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by kearmau5** [reisxd/revanced-builder#578] opened 2022-12-09 10:31 UTC
Bug in android version

Just normal android installation method
When i select YouTube 

**revanced-builder Version: latest 

Android 11
![Screenshot_2022-12-09-11-26-22-339_com android chrome](https://user-images.githubusercontent.com/78478945/206682164-ddb694fc-a31b-4280-9f97-c9b7b54c4aef.jpg)

**Comment by Velcorn** [comment] 2022-12-09 11:16
The ReVanced repo got DMCA'd, so the builder won't work anymore

**Comment by reisxd** [comment] 2022-12-09 11:47
Dupe of #576.

**Closed by reisxd** 2022-12-09 11:47 UTC
