### ISSUE TITLE
error while patching youtube 

### ISSUE THREAD

**Issue by vo1d-7bin** [reisxd/revanced-builder#322] opened 2022-08-25 17:36 UTC
![image](https://user-images.githubusercontent.com/100482403/186732136-dd010514-a441-4196-b048-e03f48140b03.png)

**Comment by reisxd** [comment] 2022-08-26 11:44
Made a new release to see what's actually happening in the back and to fix the issue.

**Comment by reisxd** [comment] 2022-08-28 05:55
Closing because this issue occurs randomly and when I tried to reproduce, it would work and not display that message.

**Closed by reisxd** 2022-08-28 05:55 UTC
