### ISSUE TITLE
Trying to mount ReVanced... with root method doesn't work

### ISSUE THREAD

**Issue by denunity** [reisxd/revanced-builder#323] opened 2022-08-26 12:24 UTC
![Screenshot_2022-08-26-15-21-10-914_com.android.chrome.jpg](https://user-images.githubusercontent.com/112175656/186902568-836a231d-ffb3-4cdf-af83-cd2db17bfcc7.jpg)![Screenshot_2022-08-26-15-21-03-876_com.termux.jpg](https://user-images.githubusercontent.com/112175656/186902603-5677cb70-f8ed-4563-a948-d4bd9ad0c63c.jpg)

**Comment by reisxd** [comment] 2022-08-26 12:26
Dupe of #239

**Closed by reisxd** 2022-08-26 12:26 UTC

**Comment by denunity** [comment] 2022-08-26 12:28
> Dupe of #239

Still didn't help:(

**Comment by denunity** [comment] 2022-08-26 12:48
> Try updating Builder using `./revanced-builder.sh update`

That didn't help either, same error;(
