### ISSUE TITLE
Builder fails when trying to build TicTok on Android/Termux

### ISSUE THREAD

**Issue by the-nothingman** [reisxd/revanced-builder#359] opened 2022-09-01 16:43 UTC
**Describe the bug**
Trying to build tictok using termux and the android method as described in the wiki keeps failing.

**To Reproduce**

1. Go to 'termux'
2. run "./revanced-builder.sh"
3. when the gui opens in web browser once it gets to the point where there should be patches to select the menu is blank
4. when going back to termux to see what went wrong this error was there:

~ $ ./revanced-builder.sh
[revanced-builder] Already gotten storage access.
[revanced-builder] Node.js and JDK already installed.
[revanced-builder] revanced-builder found.
[revanced-builder] All checks done.

[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'patches')
    at getPatchesList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:41:74)
    at getPatchList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:73:17)
    at getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getPatches.js:23:31)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:158:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

Tested Building youtube and reddit to see if they would work properly and they built fine (also another minor bug building Reddit does not give a recommended app version when showing files to download)

**Comment by reisxd** [comment] 2022-09-01 16:47
Dupe of #358

**Closed by reisxd** 2022-09-01 16:47 UTC
