### ISSUE TITLE
Error when trying to mount ReVanced (YT app isnt installed)

### ISSUE THREAD

**Issue by imsaku** [reisxd/revanced-builder#439] opened 2022-09-19 19:49 UTC
An error occured:Error: Command failed: su -mm -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'mount: bad /etc/fstab: No such file or directoryat ChildProcess.exithandler (node:child_process:398:12)at ChildProcess.emit (node:events:527:28)at maybeClose (node:internal/child_process:1092:16)at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by reisxd** [comment] 2022-09-19 19:54
Dupe of #213.

**Closed by reisxd** 2022-09-19 19:54 UTC
