### ISSUE TITLE
Application not launching for Linux

### ISSUE THREAD

**Issue by jgmGit** [reisxd/revanced-builder#121] opened 2022-08-02 10:44 UTC
The application fails to start on Linux (Ubuntu 22.04). It launches the first time, but when I try to relaunch it fails to load.
I am using the latest version `v2.1.2`

![image](https://user-images.githubusercontent.com/12555816/182356075-895c9cbc-dee4-4556-baa9-cbfac02ca046.png)

When I start from command line
```

revanced-builder$ ./Run\ ReVanced-Builder.sh 
Unknown property overflow-x
Unknown property overflow-x
Invalid value: alignItems:  "23"
(node:51245) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `qode --trace-warnings ...` to show where the warning was created)
```

**Comment by Virusmater** [comment] 2022-08-03 10:48
Try to user AppRun executable

**Comment by jgmGit** [comment] 2022-08-03 12:16
@Virusmater It is the same affect for me. When I launch the `AppRun` file. Is there some way to enable more logging ? 

Probably have to do a restart of the computer again to get the application working the second time.

**Comment by JonLit** [comment] 2022-08-03 16:23
> Try to user AppRun executable

then I just get a black window
using Garuda Linux (Arch-based, KDE, wayland, AMD GPU)

**Comment by Rtizer-9** [comment] 2022-08-04 10:04
This whole setup is about automation of main repo so it's prone to errors which you can get if commands are not verbose enough to tell you when script is encountering any error.

This is happening either because at first your phone wasn't connected/adb  isn't properly installed in case of rooted phone/ or the process got interrupted inbetween OR you opened different file instead of run revanced leading to an empty to revanced folder which will lead to bash error next time you run the script since folder is already there.

Solution: delete revanced folder and run adb kill-server if you're using a rooted phone and then connect the phone before running the script. I encountered same thing last night and this worked.

**Comment by reisxd** [comment] 2022-08-04 10:24
> This is happening either because at first your phone wasn't connected/adb isn't properly installed in case of rooted phone/ or the process got interrupted inbetween OR you opened different file instead of run revanced leading to an empty to revanced folder which will lead to bash error next time you run the script since folder is already there.

Wrong, this happens at the startup of the tool, and theres no way to debug this unless the user runs from source and tries to get the error stack. This might also be caused by QT5, which won't give an error to the NodeJS side.

**Comment by jgmGit** [comment] 2022-08-04 10:26
> > This is happening either because at first your phone wasn't connected/adb isn't properly installed in case of rooted phone/ or the process got interrupted inbetween OR you opened different file instead of run revanced leading to an empty to revanced folder which will lead to bash error next time you run the script since folder is already there.
> 
> Wrong, this happens at the startup of the tool, and theres no way to debug this unless the user runs from source and tries to get the error stack. This might also be caused by QT5, which won't give an error to the NodeJS side.

Yes it seems to be case. My phone was always connected and it deleted the cache folder. 

@reisxd  Can you describe / update the readme on how to  build the application, I can give it a try.

**Comment by reisxd** [comment] 2022-08-04 10:28
> > > This is happening either because at first your phone wasn't connected/adb isn't properly installed in case of rooted phone/ or the process got interrupted inbetween OR you opened different file instead of run revanced leading to an empty to revanced folder which will lead to bash error next time you run the script since folder is already there.
> > 
> > 
> > Wrong, this happens at the startup of the tool, and theres no way to debug this unless the user runs from source and tries to get the error stack. This might also be caused by QT5, which won't give an error to the NodeJS side.
> 
> Yes it seems to be case. My phone was always connected and it deleted the cache folder.
> 
> @reisxd Can you describe / update the readme on how to build the application, I can give it a try.

Clone the project, install NodeJS 16+ if you haven't, install the modules using `npm i` and modify the src/index.js to log the error (add `console.log(reason);` after the 26th line) and if you get an error, please send it here.

**Comment by Rtizer-9** [comment] 2022-08-04 10:30
If there's a revanced folder already present by unfinished script run then the script doesn't work. The solution is to delete the revanced folder and then start again and it work. In case of adb server issues ... issuing adb kill-server and then connecting the rooted phone works. I guess you'll have to add some command to force the script to either delete that folder right away or maybe overwrite which imo can leads few more errors when other files are present with different older versions/names maybe.

**Comment by Rtizer-9** [comment] 2022-08-04 10:32
And as I previously mentioned all the prerequisites should be properly installed and have proper defined paths in env variable so that the script doesn't encounter any error.

**Comment by jgmGit** [comment] 2022-08-04 10:41
@reisxd I get this error

`node --version
v16.16.0`

$ node src/index.js 
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/user/Downloads/revanced-builder/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node: undefined symbol: _ZN4qode9qode_argvE
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/Downloads/revanced-builder/node_modules/@nodegui/nodegui/dist/lib/utils/addon.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by reisxd** [comment] 2022-08-04 10:46
> @reisxd I get this error
> 
> `node --version v16.16.0`
> 
> ```
> $ node src/index.js 
> node:internal/modules/cjs/loader:1189
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: /home/user/Downloads/revanced-builder/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node: undefined symbol: _ZN4qode9qode_argvE
>     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/user/Downloads/revanced-builder/node_modules/@nodegui/nodegui/dist/lib/utils/addon.js:3:15)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
>   code: 'ERR_DLOPEN_FAILED'
> }
> ```

Can you try running `npx qode ./dist?`

**Comment by jgmGit** [comment] 2022-08-04 10:48
@reisxd Tried this `revanced-builder$ npx qode src/index.js` it seems to start the application. Will update you when I get the errors.

**Comment by reisxd** [comment] 2022-08-04 11:11
> @reisxd At-least when I run from the source code, there is no issues at all. I can kill and relaunch the application all the time, without any issues.

That's weird.. Try running it with `npm start` first then if that works, try `npm run build && npx qode ./dist`.

**Comment by jgmGit** [comment] 2022-08-04 12:01
When I do `npm start`
```
$ npm start

> revanced-builder-gui@1.0.0 start
> webpack && qode ./dist/index.js

asset nodegui_core-fe828ab353fe9605ab65443359c34430.node 8.82 MiB [emitted] (auxiliary name: main)
asset index.js 2.74 MiB [emitted] (name: main)
407 modules

WARNING in ./node_modules/node-fetch/lib/index.js 163:11-38
Module not found: Error: Can't resolve 'encoding' in '/home/johny/Downloads/revanced-builder/node_modules/node-fetch/lib'
 @ ./src/utils/builder.js 5:17-70
 @ ./src/index.js 10:22-51

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 1 warning in 1783 ms
Unknown property overflow-x
Unknown property overflow-x
Invalid value: alignItems:  "23"
(node:61361) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `qode --trace-warnings ...` to show where the warning was created)
/home/johny/Downloads/revanced-builder/node_modules/@nodegui/qode/binaries/qode: symbol lookup error: /home/johny/Downloads/revanced-builder/dist/nodegui_core-fe828ab353fe9605ab65443359c34430.node: undefined symbol: _ZdlPvm, version Qt_5
```

**Comment by reisxd** [comment] 2022-08-04 12:05
> @reisxd When I do `npm start`
> 
> It has the same issue, it is stuck at the black screen
> 
> ```
> $ npm start
> 
> > revanced-builder-gui@1.0.0 start
> > webpack && qode ./dist/index.js
> 
> asset nodegui_core-fe828ab353fe9605ab65443359c34430.node 8.82 MiB [emitted] (auxiliary name: main)
> asset index.js 2.74 MiB [emitted] (name: main)
> 407 modules
> 
> WARNING in ./node_modules/node-fetch/lib/index.js 163:11-38
> Module not found: Error: Can't resolve 'encoding' in '/home/user/Downloads/revanced-builder/node_modules/node-fetch/lib'
>  @ ./src/utils/builder.js 5:17-70
>  @ ./src/index.js 10:22-51
> 
> 1 warning has detailed information that is not shown.
> Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
> 
> webpack 5.74.0 compiled with 1 warning in 1783 ms
> Unknown property overflow-x
> Unknown property overflow-x
> Invalid value: alignItems:  "23"
> (node:61361) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
> (Use `qode --trace-warnings ...` to show where the warning was created)
> /home/user/Downloads/revanced-builder/node_modules/@nodegui/qode/binaries/qode: symbol lookup error: /home/user/Downloads/revanced-builder/dist/nodegui_core-fe828ab353fe9605ab65443359c34430.node: undefined symbol: _ZdlPvm, version Qt_5
> ```

That's weird... I have no idea why does this happen and because I use Windows, I'm not able to reproduce.

**Comment by Rtizer-9** [comment] 2022-08-04 12:30
@jgmGit if you have any component involved in this whole code compiled in an unusual manner like qt compiled from pip instead of official repo version then try reinstalling those components.

When you're done with that, reboot properly just to make sure all changes are applied properly and then again check for prerequisites.

If by any chance you ran the script first and forgetting that some prerequisite wasn't installed and then tried installing them, install all those first > delete revanced folder completely> reboot > then download and rerun the script.

If you're using some different shell then try using default bash.

Whatever you try first delete that cache folder revanced and then rerun. Adb kill-server will be needed too if phone was connected and script didn't and then you tried again.

**Comment by jgmGit** [comment] 2022-08-04 12:52
> @jgmGit if you have any component involved in this whole code compiled in an unusual manner like qt compiled from pip instead of official repo version then try reinstalling those components.
> 
> When you're done with that, reboot properly just to make sure all changes are applied properly and then again check for prerequisites.
> 
> If by any chance you ran the script first and forgot that some prerequisite wasn't installed and then tried installing them, install all those first > delete revanced folder completely> reboot > then download and rerun the script.
> 
> If you're using some different shell then try using default bash. (Zsh is compatible in most cases but fish causes issue many times)
> 
> Whatever you try first delete that cache folder (every single time you rerun the script) revanced and then rerun. Adb kill-server will be needed too if phone was connected and script didn't work and then you tried again.

Same thing. Cloned the project and rebooted. Stuck in the black screen.

**Comment by Rtizer-9** [comment] 2022-08-04 13:12
I mean you won't need to clone the project completely just download the zips given in releases and it'll work. Try searching the node error messages you're getting and you'll find many results.

**Comment by reisxd** [comment] 2022-08-04 14:47
I have rewritten the tool to be a webapp, so closing this issue.

**Closed by reisxd** 2022-08-04 14:47 UTC
