### ISSUE TITLE
Trying to mount revanced....

### ISSUE THREAD

**Issue by some1onLSD** [reisxd/revanced-builder#309] opened 2022-08-24 22:05 UTC
When the patching is finished and arrives to the mounting process it throws an error in termux and the patcher freezes:

[builder] An error occured.
Error: Command failed: su -mm -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'
mount: bad /etc/fstab: No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by some1onLSD** [comment] 2022-08-24 23:15
And I also get this warning in the installer

![Screenshot_20220825-001314_Chrome~2](https://user-images.githubusercontent.com/74503778/186539727-d82f5f8b-ac53-4f8b-b8cf-19333e8822d9.png)

**Comment by reisxd** [comment] 2022-08-25 04:41
Dupe of #213.

**Closed by reisxd** 2022-08-25 04:41 UTC
