### ISSUE TITLE
Warn wetter patches are not showing

### ISSUE THREAD

**Issue by lewdpatriot** [reisxd/revanced-builder#360] opened 2022-09-01 18:07 UTC
**Describe the bug**
As the title says

**Screenshots**
![Screenshot_2022-09-01-23-10-35-54_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/63286528/187982648-2973e2fb-6fa2-4dc5-89a4-b2bb66d21c92.jpg)

**revanced-builder Version:** 
V3.3.7

**Desktop (please complete the following information):**

- OS: android
- Version: 11

**Additional context**
Error message

[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'patches')
    at getPatchesList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:49:74)
    at getPatchList (/data/data/com.termux/files/home/revanced-builder/utils/PatchListRememberer.js:81:17)
    at getPatches (/data/data/com.termux/files/home/revanced-builder/wsEvents/getPatches.js:23:31)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/revanced-builder/index.js:158:9)

**Comment by reisxd** [comment] 2022-09-01 18:23
Dupe of #358

**Closed by reisxd** 2022-09-01 18:23 UTC
