### ISSUE TITLE
App shuts down immediately

### ISSUE THREAD

**Issue by melvas6** [reisxd/revanced-builder#88] opened 2022-07-26 13:54 UTC
I installed the youtube apk on the phone first and then installed the revanced apk of the same version (17.29.34). But when I open revanced, it immediately shutsdown. Kindly help.

**Comment by reisxd** [comment] 2022-07-26 14:03
This issue is caused by microg-support patch being broken and is now fixed (no new release for now by the ReVanced team though, use an older version of YouTube).

**Closed by reisxd** 2022-07-26 14:03 UTC

**Comment by melvas6** [comment] 2022-07-26 15:03
> ~Try using an older apk.~ Wait, are you building rooted or not?

Non-rooted
