### ISSUE TITLE
Ratelimited from Github

### ISSUE THREAD

**Issue by mctaylors** [reisxd/revanced-builder#579] opened 2022-12-09 13:33 UTC
```
Error: You got ratelimited from GitHub
...Completely? What did you even do?
    at getDownloadLink (C:\snapshot\revanced-builder\utils\FileDownloader.js:52:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async downloadFiles (C:\snapshot\revanced-builder\utils\FileDownloader.js:156:26)
    at async updateFiles (C:\snapshot\revanced-builder\wsEvents\updateFiles.js:68:3)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:163:9)
```
**revanced-builder Version:** v3.5.0

**Desktop:**

- OS: Windows
- Version: 10

**Comment by robalmeister** [comment] 2022-12-09 13:34
Because github gave DMCA to one project - revanced-patcher which is the most important

**Comment by reisxd** [comment] 2022-12-09 14:01
Dupe of #576.

**Closed by reisxd** 2022-12-09 14:01 UTC
