### ISSUE TITLE
Latest rooted build/patching caused youtube to crash

### ISSUE THREAD

**Issue by binoysankar** [reisxd/revanced-builder#373] opened 2022-09-04 02:58 UTC
**Describe the bug**
Install latest youtube from playstore - version ```17.34.35``` currently.
When doing a rooted build the screen to pick youtube version is not displaying. It automatically downloads some version and patching it. This eventually causes youtube to crash when opening. Seems there is a version mismatch happening.
To verify this I tried non-rooted version build process and there the apk version created says ```17.33.42``` which is not the latest youtube version in playstore. But non-rooted process works as its a separate apk and no patching needed with the actual apk from playstore for the rooted build.

**To Reproduce**
1. Install/update youtube from playstore
2. Follow the rooted patching process for Android
3. Open youtube after patching
4. Youtube crashes even after restarting phone

**Comment by reisxd** [comment] 2022-09-04 04:57
Dupe of #368, and 

> When doing a rooted build the screen to pick youtube version is not displaying. It automatically downloads some version and patching it. This eventually causes youtube to crash when opening. Seems there is a version mismatch happening.

It doesn't have a version mismatch, but it actually downloads the version you have on yout device. And 17.34.xx is broken with the patches.

**Closed by reisxd** 2022-09-04 04:57 UTC
