### ISSUE TITLE
Error when trying to download pathched apk

### ISSUE THREAD

**Issue by pushkargogte** [reisxd/revanced-builder#237] opened 2022-08-15 12:09 UTC
**Describe the bug**
After successfully building patched youtube apk, when clicked on download button it gives error.

**To Reproduce**

1. Go to 'Patching page'
2. Click on 'Download button'
3. New page opens in new tab

**Screenshots**
![image](https://user-images.githubusercontent.com/16486468/184632218-a16d7ccf-1ccb-4918-8d41-48f4fd3aa581.png)
![image](https://user-images.githubusercontent.com/16486468/184632258-d7080178-ebc8-4344-8859-ebb649f824d6.png)
![image](https://user-images.githubusercontent.com/16486468/184632748-0bba3ff3-63d0-40ff-966d-9ba2cbf39198.png)

**revanced-builder Version:** [e.g. v1.2.10]
v3.1.8

**Desktop (please complete the following information):**
Assembled PC
8gb ram
2gb graphics card
256gb SSD
500gb HDD

- OS: [e.g. Windows]
Windows
- Version: [e.g. 10]
10.0.19044.1889

**Additional context**

**Comment by reisxd** [comment] 2022-08-15 12:13
Dupe of #224.

**Closed by reisxd** 2022-08-15 12:13 UTC
