### ISSUE TITLE
error mounting revanced youtube

### ISSUE THREAD

**Issue by Mickey-Kings** [reisxd/revanced-builder#390] opened 2022-09-07 09:11 UTC
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: Command failed: su -mm -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'
mount: bad /etc/fstab: No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by reisxd** [comment] 2022-09-07 09:15
Dupe of #213.

**Closed by reisxd** 2022-09-07 09:15 UTC
