### ISSUE TITLE
Revanced error while running from windows

### ISSUE THREAD

**Issue by akshy697** [reisxd/revanced-builder#451] opened 2022-09-23 10:12 UTC
[builder] An error occured.
TypeError: Cannot read properties of null (reading 'replace')
    at downloadApp (C:\snapshot\revanced-builder\utils\downloadApp.js:10:39)
    at downloadApp (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:31:36)
    at getAppVersion (C:\snapshot\revanced-builder\wsEvents\getAppVersion.js:116:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (C:\snapshot\revanced-builder\index.js:187:9)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by reisxd** [comment] 2022-09-23 10:47
Please give more information.

**Comment by shrihanDev** [comment] 2022-09-23 13:37
Cannot reproduce on latest version + possible duplicate of #426

**Closed** 2022-09-23 13:37 UTC
