### ISSUE TITLE
unable to patch youtube 

### ISSUE THREAD

**Issue by LeaderbotX400** [reisxd/revanced-builder#594] opened 2022-12-16 00:09 UTC
**Describe the bug**
I am trying to patch youtube and it spits out this error:

**To Reproduce**

1. Run the latest version of Revanced Patcher
2. Select all patches (except Debugging and Theme) 
3. Use youtube 1.45.36

**Screenshots**
![image](https://user-images.githubusercontent.com/34589843/207992692-107e1101-3175-4d48-8e7e-26b1c1044014.png)

**revanced-builder Version:** 3.6.0

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**
I have tried the pre built windows exe as well as running from source and docker all to no avail

**Comment by reisxd** [comment] 2022-12-16 05:16
Dupe of #593.

**Closed by reisxd** 2022-12-16 05:16 UTC
