### ISSUE TITLE
Rooted version started crashing

### ISSUE THREAD

**Issue by UltraHQ** [reisxd/revanced-builder#372] opened 2022-09-03 21:42 UTC
**Describe the bug**
It was working fine some days ago. I'm not sure if YouTube updated the last days, but for some reason I cannot use revanced rooted version anymore. I have already rebuilt and re-installed YouTube a couple of times to make sure.
The same thing applies to YouTube music.

**Additional context**
My YouTube Package version is on 17.34.35
I've also changed my android props to pixel 6 pro - not sure if this is the problem, as unpatched YouTube works perfectly fine.

**Comment by reisxd** [comment] 2022-09-03 21:50
Dupe of #368.

**Closed by reisxd** 2022-09-03 21:50 UTC
