### ISSUE TITLE
vid ads failed :/

### ISSUE THREAD

**Issue by THE-L1NUX-USER** [reisxd/revanced-builder#520] opened 2022-10-22 12:21 UTC
![image](https://user-images.githubusercontent.com/100482403/197338691-40a08074-72fa-4ec7-9b04-e10ffd2cfa42.png)
to reproduce 
1 select all patches 
2 wait for the build 
3 check logs

**Comment by reisxd** [comment] 2022-10-22 13:21
Dupe of #515.

**Closed by reisxd** 2022-10-22 13:22 UTC
