### ISSUE TITLE
custom-branding & theme failed

### ISSUE THREAD

**Issue by origamiofficial** [reisxd/revanced-builder#399] opened 2022-09-08 16:19 UTC
**Describe the bug**
Whenever I try to patch the YouTube app with custom-branding & theme patches it fails. I've tried it on both Android & Windows, and I got same result always.

**To Reproduce**
Just try to patch YouTube as usual with custom-branding & theme patches.

**Terminal Output**
```bash
[builder] SEVERE: custom-branding failed:
[builder] app.revanced.patcher.patch.PatchResultError: Invalid option value type: java.lang.String, expected null
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:315)
[builder] at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:45) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:331) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:96) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
[builder] at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: app.revanced.patcher.patch.InvalidTypeException: Invalid option value type: java.lang.String, expected null at app.revanced.patches.youtube.layout.branding.icon.patch.CustomBrandingPatch$Companion.getAppIconPath(CustomBrandingPatch.kt:116) at app.revanced.patches.youtube.layout.branding.icon.patch.CustomBrandingPatch$Companion.access$getAppIconPath(CustomBrandingPatch.kt:77)
[builder] at app.revanced.patches.youtube.layout.branding.icon.patch.CustomBrandingPatch.getIconStream(CustomBrandingPatch.kt:69) at app.revanced.patches.youtube.layout.branding.icon.patch.CustomBrandingPatch.execute(CustomBrandingPatch.kt:45) at app.revanced.patches.youtube.layout.branding.icon.patch.CustomBrandingPatch.execute(CustomBrandingPatch.kt:18) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:310) ... 16 more
[builder] INFO: disable-fullscreen-panels succeeded
[builder] INFO: old-quality-layout succeeded
[builder] SEVERE: theme failed:
[builder] app.revanced.patcher.patch.PatchResultError: null was passed into an option that requires a value at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:315) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:45) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:331) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
[builder] at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:96) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[builder] at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: app.revanced.patcher.patch.RequirementNotMetException: null was passed into an option that requires a value at app.revanced.patcher.patch.RequirementNotMetException.(PatchOption.kt) at app.revanced.patcher.patch.PatchOption.getValue(PatchOption.kt:86)
[builder] at app.revanced.patches.youtube.layout.theme.patch.ThemePatch$Companion.getTheme(ThemePatch.kt:66) at app.revanced.patches.youtube.layout.theme.patch.ThemePatch.execute(ThemePatch.kt:23) at app.revanced.patches.youtube.layout.theme.patch.ThemePatch.execute(ThemePatch.kt:15)
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:310) ... 16 more
```

**revanced-builder Version:** [e.g. v1.2.10]
[v3.4.3](https://github.com/reisxd/revanced-builder/releases/tag/v3.4.3)

**Desktop (please complete the following information):**

- OS: Windows & Android
- Version: W11 & A13

**Additional context**
custom-branding succeeded but theme failed in RB v3.4.2 - v3.4.0

**Comment by reisxd** [comment] 2022-09-08 16:24
Dupe of #396.

**Closed by reisxd** 2022-09-08 16:24 UTC
