### ISSUE TITLE
Fails to build - Revanced.Delete, device in use.

### ISSUE THREAD

**Issue by FeroxFoxxo** [reisxd/revanced-builder#406] opened 2022-09-11 00:30 UTC
![Screenshot_20220911-122922_Chrome](https://user-images.githubusercontent.com/51069105/189506360-a05e8235-442b-4543-a025-ea65c4a777d4.png)

**Comment by reisxd** [comment] 2022-09-11 04:59
Dupe of #332

**Closed by reisxd** 2022-09-11 04:59 UTC
