### ISSUE TITLE
Rate limited before selected patch

### ISSUE THREAD

**Issue by MikuNoLimit87** [reisxd/revanced-builder#577] opened 2022-12-09 08:04 UTC
![Screenshot_20221209-145101_Chrome](https://user-images.githubusercontent.com/107130800/206652309-1de0f2f0-ef63-4a3f-a6fa-b6d5903ba28f.png)

**Comment by reisxd** [comment] 2022-12-09 08:04
Dupe of #576.

**Closed by reisxd** 2022-12-09 08:04 UTC
