### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by drbenco** [reisxd/revanced-builder#722] opened 2023-04-27 21:55 UTC
**Describe the bug**
Tried to patch youtbe but it did not work.
**Screenshots**
![image](https://user-images.githubusercontent.com/101985381/234998750-7d2618b7-0f2f-49c6-b08a-7240c10a218d.png)

**revanced-builder Version:** lastest

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**

Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Lucas559-noob** [comment] 2023-04-28 00:20
Same here, Windows 8.1, with Youtube

**Comment by Lau893** [comment] 2023-04-28 00:48
same here on windows 10, and the same kind of errors on the revanced manager

**Comment by alekh1stzoom** [comment] 2023-04-28 04:24
Getting same issue on Ubuntu 20.04 with vanced youtube

**Comment by Wrthlor** [comment] 2023-04-28 05:59
Also same error. 
OS: Windows 10, ver. 21H2
App: Youtube 18.15.40

![image](https://user-images.githubusercontent.com/54452494/235065998-939e5151-318a-4458-99fc-2440f274da04.png)

**Comment by CorazaCRZ** [comment] 2023-04-28 06:06
Same here. W10

**Comment by mooms06** [comment] 2023-04-28 12:31
Duplicate of https://github.com/reisxd/revanced-builder/issues/700

Next time please search before opening an issue.

**Closed** 2023-04-30 05:09 UTC
