### ISSUE TITLE
Failure to mount rooted revanced

### ISSUE THREAD

**Issue by machtoners** [reisxd/revanced-builder#281] opened 2022-08-21 08:03 UTC
[builder] An error occured.
Error: Command failed: su -c '"/data/adb/service.d/mount_revanced_com.google.android.youtube.sh"'
mount: '/data/adb/revanced/com.google.android.youtube.apk'->'/data/app/~~2Jz5nRVMtzuNXSqjHaTxpQ==/com.google.android.youtube--_BVKjRDvMsfxoiuTZNw-A==/base.apk': No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
[builder] Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by reisxd** [comment] 2022-08-21 09:54
Dupe of #222

**Closed** 2022-08-21 09:54 UTC
