### ISSUE TITLE
Revanced builder not able to reinstall..

### ISSUE THREAD

**Issue by B0TRICK** [reisxd/revanced-builder#428] opened 2022-09-16 04:34 UTC
**Describe the bug**
I want to rebuild revanced builder for YouTube.

**Screenshots**
![Screenshot_20220916-095117_Brave](https://user-images.githubusercontent.com/113281799/190557097-4ec8d477-5fe6-419a-ae77-bf23ffc843e7.png)

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (mobile ):**

- OS: [Android 12]
- Version: [12]

**Additional context**
I need extra futures for my YouTube so I upgraded to revanced builder now it's not able to download.

**Comment by reisxd** [comment] 2022-09-16 05:15
Dupe of #426

**Closed by reisxd** 2022-09-16 05:15 UTC
